version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: cryptowatch-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    container_name: cryptowatch-redis
    ports:
      - "6379:6379"
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cryptowatch-sqlserver
    environment:
      SA_PASSWORD: "CryptoW@tch2024"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mongo:
    image: mongo
    container_name: cryptowatch-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
networks:
  default:
    driver: bridge