version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: cryptowatch-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    container_name: cryptowatch-redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge